# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.9
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            pip install -r requirements.txt
            pytest finance.py

  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - setup_remote_docker:
            version: 19.03.13
      - run:
          name: "Image creation"
          command: docker build -t mathonweb/finance .

  deploy:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
            version: 19.03.13
      - run:
          name: "Image push to DockerHub"
          command: docker push mathonweb/finance:latest

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  workflow:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          type: approval
          requires:
            - build
